version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: PythonApprentice
    ports:
      - "8080:8080" # Access code-server
    volumes:
      - .:/workspace
    environment:
      - PASSWORD=code4life # Optional: Secure access
    command: >
      code-server --bind-addr 0.0.0.0:8080 /workspace
